spring.application.name=gramutsav

server.port=8080

#spring.datasource.url=jdbc:postgresql://localhost:5432/GramUtsav
spring.datasource.url=postgresql://neondb_owner:npg_R9rqVYzkf7SA@ep-lively-meadow-ap3j9pax.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hemantnagare01@gmail.com
spring.mail.password=iner qbfb ixow fouc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

